server:
  port: 8080
  servlet:
    context-path: /spt

## 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1790720818zwj
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 设置ehcache的配置
  cache:
    ehcache:
      config: classpath:ehcache.xml

  # 热部署
  devtools:
    restart:
      enabled: true
      # 设置重启的目录，添加目录的文件需要restart
      additional-paths: src/main/java
      # 解决项目自动编译后接口报404问题
      poll-interval: 3000
      quiet-period: 1000


# mybatis配置
mybatis:
  # 映射文件的存放位置
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.spt.springboot.pojo
  configuration:
    # 下划线转驼峰配置
    map-underscore-to-camel-case: true

# pageHelper
pagehelper:
  helper-dialect: mysql

# 显示dao 执行sql语句
logging:
  level:
    com:
      spt:
        springboot:
          dao: debug